name: CI

on: 
  push:
    branches:    
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Deploy heroku stage
      run: |
        echo Ready to deploy to heroku.